### ISSUE TITLE
Duplicate method names in cobertura-coverage.xml cause Jenkins coverage plugin parsing failure

### ISSUE THREAD

**Issue by cchangenot** [AriPerkkio/ast-v8-to-istanbul#169]
## Context

- **vitest** with `coverage-v8`
- **ast-v8-to-istanbul** v1.0.3
- cobertura report

## Problem

Since [this change in ast-v8-to-istanbul#165](https://github.com/AriPerkkio/ast-v8-to-istanbul/pull/165), it is now possible to have multiple methods with the same name within the same class in the generated `cobertura-coverage.xml`.

This is not supported by the **Jenkins coverage plugin**, which throws the following error:

```
Caused: edu.hm.hafner.coverage.CoverageParser$ParsingException: A duplicate element was detected
in '/coverage/cobertura-coverage.xml' while parsing this coverage report. This typically indicates
a problem with the coverage producer tool. As a temporary workaround, you can set ignoreErrors=true
to skip such elements. Please report this issue to the coverage producer (e.g., gcovr, Go coverage)
or create an issue at https://github.com/jenkinsci/coverage-model/issues.

IllegalArgumentException: There is already the same child [METHOD] constructor()V <0> with the name
constructor()V in [CLASS] models.ts <1, LINE: 100.00% (1/1)>

java.lang.IllegalArgumentException: There is already the same child [METHOD] constructor()V <0>
with the name constructor()V in [CLASS] models.ts <1, LINE: 100.00% (1/1)>
```

## Root Cause

The Cobertura XML format does not support duplicate method names within the same `<class>` element. The Jenkins coverage plugin enforces this constraint and fails when it encounters duplicates.

This can happen easily in the following scenarios:

- **Multiple classes with a constructor in the same file** — each `constructor()` ends up with the same signature (`constructor()V`) under the same `<class>` node representing the file.
- **JavaScript getter/setter pairs** — e.g. `get foo() {}` and `set foo(bar) {}` both map to the same method name `foo`.

## Expected Behavior

Each method entry in the generated `cobertura-coverage.xml` should have a unique name within its parent `<class>` element, for example by appending a disambiguating suffix such as the line number, a counter, or the kind (getter/setter/constructor index).

## Actual Behavior

Multiple methods share the same name (e.g. `constructor()V`) inside the same `<class>` block, producing invalid Cobertura XML that downstream consumers (such as the Jenkins coverage plugin) cannot parse.

## Possible Fix

Deduplicate or disambiguate method names at the point of Cobertura XML generation, for example:

- `constructor()V` → `constructor()V`, `constructor()V#2`, `constructor()V#3`, …
- `get foo` / `set foo` → `get foo`, `set foo`

## Reproduction

1. Create a TypeScript file with multiple classes, each having a constructor:

```ts
// models.ts
export class Foo {
  constructor(public name: string) {}
}

export class Bar {
  constructor(public id: number) {}
}
```

2. Run vitest with `coverage-v8`.
3. Inspect the generated `cobertura-coverage.xml` — both constructors appear under the same `<class name="models.ts">` with identical method names.
4. Feed the report to the Jenkins coverage plugin → parsing exception.

**Comment by AriPerkkio** [comment]
cc. @arlyon

**Comment by dezsiszabi** [comment]
Just wanted to add my +1 as well. Investigating a Cobertura report failure at work after doing an `npm upgrade` and my suspicion led me to this library.

**Comment by dezsiszabi** [comment]
I reverted the library to 1.0.0 which was the version we used before I did an `npm upgrade` and I see that the method names in the cobertura report xml are different in the old version

The old version generated method named like:
- `(anonymous_0)`
- `(anonymous_1)`

The new version now correctly generates the method names, but getter/setters are not considered because those end up with the same method name in the cobertura report.

So I can confirm that unfortunately the new version of this library breaks cobertura reports in vite and the `recordCoverage` Jenkins plugin can't parse them anymore.

**Comment by AriPerkkio** [comment]
@cchangenot @dezsiszabi, don't you get the same error with `1.0.0` before the fix with following code?

```ts
if (Math.random() > 0.5) {
  function example() {
    return 2;
  }
  example();
} else {
  function example() {
    return 1;
  }

  example();
}
```

Produces XML report with duplicate identifiers:

```xml
    <package name="main" line-rate="0.6" branch-rate="0.5">
      <classes>
        <class name="source.ts" filename="src/source.ts" line-rate="0.6" branch-rate="0.5">
          <methods>
            <method name="example" hits="1" signature="()V">
              <lines>
                <line number="2" hits="1"/>
              </lines>
            </method>
            <method name="example" hits="0" signature="()V">
              <lines>
                <line number="7" hits="0"/>
              </lines>
            </method>
          </methods>
          <lines>
            <line number="1" hits="1" branch="true" condition-coverage="50% (1/2)"/>
            <line number="3" hits="1" branch="false"/>
            <line number="5" hits="1" branch="false"/>
            <line number="8" hits="0" branch="false"/>
            <line number="11" hits="0" branch="false"/>
          </lines>
        </class>
      </classes>
    </package>
```

**Comment by cchangenot** [comment]
In my case no, it's always rendered as `(anonymous_1)` and `(anonymous_2)` for the method name.
I tested with version `1.0.0`, `1.0.2`, and it's even working with `1.0.3`.

**Comment by cchangenot** [comment]
I also tried your code directly in a ts file instead of wrapping it inside a function. In this case, I have a compilation error from angular-compiler so I can't say...

```
✘ [ERROR] TS2393: Duplicate function implementation. [plugin angular-compiler]

    src/app/source.ts:2:11:
      2 │   function example(): number {
        ╵            ~~~~~~~


✘ [ERROR] TS2393: Duplicate function implementation. [plugin angular-compiler]

    src/app/source.ts:7:11:
      7 │   function example(): number {

```

EDIT: I used js instead of ts for the file to avoid compilation error and I have that (any version):

```xml
  <class name="source.js" filename="src/app/source.js" line-rate="0.5714" branch-rate="0.5">
    <methods>
      <method name="(anonymous_0)" hits="1" signature="()V">
        <lines>
          <line number="1" hits="1"/>
        </lines>
      </method>
      <method name="(anonymous_1)" hits="1" signature="()V">
        <lines>
          <line number="2" hits="1"/>
        </lines>
      </method>
      <method name="(anonymous_2)" hits="0" signature="()V">
        <lines>
          <line number="7" hits="0"/>
        </lines>
      </method>
    </methods>
    <lines>
      <line number="1" hits="1" branch="true" condition-coverage="50% (1/2)"/>
      <line number="2" hits="1" branch="false"/>
      <line number="3" hits="1" branch="false"/>
      <line number="5" hits="1" branch="false"/>
      <line number="7" hits="0" branch="false"/>
      <line number="8" hits="0" branch="false"/>
      <line number="11" hits="0" branch="false"/>
    </lines>
  </class>
```

**Comment by AriPerkkio** [comment]
> I used js instead of ts for the file to avoid compilation error and I have that (any version):

This isn't equivalent either as your compiler pipeline seems to be transforming the functions to anonymous ones.

**Comment by dezsiszabi** [comment]
Worth noting that in my case I was talking about an Angular 21 (typescript) project using `vitest`. `vitest` pulls in `ast-v8-to-istanbul` via `@vitest/coverage-v8`.

Now I don't know if any of this added context matters at all. All I confirmed so far is that if I downgrade ONLY the `ast-v8-to-istanbul` dependency, then the generated report doesn't contain a duplicate method name.

I'll try and create a reproduction and share it here. Although I might only have time for that on the weekend.

**Comment by cchangenot** [comment]
I have the same context as you @dezsiszabi 
Simply overriding `ast-v8-to-istanbul` to previous version in your package.json should work for you until something is fixed here.
```json
  "overrides": {
    "ast-v8-to-istanbul": "1.0.2"
  },
```

**Comment by dezsiszabi** [comment]
Created a reproduction here: https://github.com/dezsiszabi/cobertura-bug-repro

Let me know if I missed something or if it's not clear. Steps to reproduce are in the `README.md`.

**Comment by AriPerkkio** [comment]
~~@dezsiszabi could you create the reproduction without Angular? Ideally in this repository under [`test/fixtures`](https://github.com/AriPerkkio/ast-v8-to-istanbul/tree/main/test/fixtures) so that we can actually test it.~~

**Comment by AriPerkkio** [comment]
@cchangenot & @dezsiszabi, could you try if this preview release fixes the issue?

```ts
npm i https://pkg.pr.new/ast-v8-to-istanbul@170
```

**Comment by cchangenot** [comment]
No more error on my side @AriPerkkio 👍

**Comment by dezsiszabi** [comment]
@AriPerkkio thanks for the quick turnaround. I tested the new package with my project at work. It does work.

One sidenote though: https://github.com/AriPerkkio/ast-v8-to-istanbul/pull/170#discussion_r3388235123

This comment from @coderabbitai is correct.

If I have the following code:

```typescript
class Foo {
    private _selectedReleases: any;

    public get selectedReleases(): any {
        return this._selectedReleases;
    }

    public set selectedReleases(value: any) {
        this._selectedReleases = value;
    }

    public selectedReleases_2(): any {
        console.log("This is a test method");
    }
}
```

It still generates duplicate method names `selectedReleases`, `selectedReleases_2`, `selectedReleases_2`.

**EDIT**: sorry, I didn't know this AI bot is this stupid that it creates random issues when its name is mentioned.

**Comment by dezsiszabi** [comment]
Since you closed this, I assume you don't think the coderabbit finding is valid?

Or you fixed it via https://github.com/AriPerkkio/ast-v8-to-istanbul/pull/170/changes/4dadd47d08c084292b37eb5c000e144c370908a0 ?

**Comment by AriPerkkio** [comment]
Finding was valid and fixed in the PR.

**Comment by cchangenot** [comment]
Thanks for the fix !

**Comment by dezsiszabi** [comment]
Thank you @AriPerkkio
